<?php
echo $this->doctype();
?>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <meta name="viewport" id="viewport" content="width=device-width,initial-scale=1,user-scalable=no,minimal-ui">
        <meta name="apple-mobile-web-app-capable" content="yes">

        <?php echo $this->render('blocks/head.phtml'); ?>

        <script>
            var ww = screen.width; //window.innerWidth;
            if (ww < 640) {
                var scale = (ww / 640).toFixed(2);
                document.getElementById("viewport").setAttribute('content', 'width=640,user-scalable=no,minimal-ui');
            }

            var readyStart = +new Date();
            var readyQueue = []; var readyProcessed = false;
            readyHandler = function (event) {
                console.log('ready', readyProcessed, +new Date() - readyStart);
                if (readyProcessed) return;
                readyProcessed = true;
                readyQueue.forEach(function(func) { func(); });
            };

            if (window.addEventListener) {
                window.addEventListener('load', readyHandler, false);
                window.addEventListener('DOMContentLoaded', readyHandler, false);
            } else {
                window.attachEvent('onload', handler);
            }

            function _l(handler, now) {
                if (now) {
                    handler();
                } else {
                    //add to event queue
                    readyQueue.push(handler);
                }
            }
        </script>

    </head>
    <body>
        
        <?php echo $this->render('blocks/header.phtml'); ?>

        <div class="wrap push">
            <?php echo $this->layout()->content; ?>

            <?php echo $this->render('blocks/footer.phtml'); ?>
        </div>
        
        <?php echo $this->render('blocks/foot.phtml'); ?>

        <script>readyHandler();</script>

	<?php echo $this->render('blocks/analytics.phtml'); ?>
        
    </body>
</html>
